spring:
  datasource:
    name: practisedb  #数据库名
    url: jdbc:mysql://localhost:3306/practisedb?useUnicode=true&characterEncoding=utf-8&useSSL=false #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/


mybatis:
#  mapper-locations: classpath:mapper/*.xml  #配置映射文件
#  type-aliases-package: com.zhangziwa.practisesvr.model #配置实体类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  typeAliasesPackage: XXXX
  mapper-locations: classpath*:**/xml/*Mapper.xml